Organizations:

    - &Orderer
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/atlchain.com/msp
        Policies: &SampleOrgPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member', 'OrdererMSP.admin', 'OrdererMSP.peer', 'OrdererMSP.client')" # "OR('OrdererMSP.admin', 'OrdererMSP.peer', 'OrdererMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member', 'OrdererMSP.admin', 'OrdererMSP.peer', 'OrdererMSP.client')" # "OR('OrdererMSP.admin', 'OrdererMSP.peer', 'OrdererMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
                
    - &OrgA
        Name: OrgAMSP

        ID: OrgAMSP

        MSPDir: crypto-config/peerOrganizations/orga.atlchain.com/msp

        Policies: &SampleOrgPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrgAMSP.admin', 'OrgAMSP.peer', 'OrgAMSP.client', 'OrgA.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrgAMSP.admin', 'OrgAMSP.peer', 'OrgAMSP.client', 'OrgA.member')" # "OR('OrgA.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrgAMSP.admin')"

        AnchorPeers:
            - Host: 127.0.0.1
              Port: 7051

    - &OrgB
        Name: OrgBMSP

        ID: OrgBMSP

        MSPDir: crypto-config/peerOrganizations/orgb.atlchain.com/msp

        Policies: &SampleOrgPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrgBMSP.admin', 'OrgBMSP.peer', 'OrgBMSP.client', 'OrgB.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrgBMSP.admin', 'OrgBMSP.peer', 'OrgBMSP.client', 'OrgB.member')" # "OR('OrgB.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrgBMSP.admin')"

        AnchorPeers:
            - Host: 127.0.0.1
              Port: 7051


Capabilities:
    Channel: &ChannelCapabilities
        V1_1: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_2: true
        V1_1: false

Application: &ApplicationDefaults
    ACLs: &ACLsDefault
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetConfigTree: /Channel/Application/Readers
        cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Readers
        event/Block: /Channel/Application/Readers
        event/FilteredBlok: /Channel/Application/Readers

    Organizations:
    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - 127.0.0.1:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0

    Kafka:
        Brokers:
            - kafka0:9092
            - kafka1:9092
            - kafka2:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    OrdererOrg:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Orderer
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *OrgA
                    - *OrgB

    TxChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *OrgA
                - *OrgB
