General:
    LedgerType: file
    ListenAddress: 127.0.0.1
    ListenPort: 7050
    TLS:
        Enabled: false
        PrivateKey: crypto-config/ordererOrganizations/atlchain.com/orderers/orderer.atlchain.com/tls/server.key
        Certificate: crypto-config/ordererOrganizations/atlchain.com/orderers/orderer.atlchain.com/tls/server.crt
        RootCAs:
          - crypto-config/ordererOrganizations/atlchain.com/orderers/orderer.atlchain.com/tls/ca.crt
        ClientAuthRequired: false
        ClientRootCAs:

    Keepalive:
        ServerMinInterval: 60s
        ServerInterval: 7200s
        ServerTimeout: 20s

    LogLevel: info
    LogFormat: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
    GenesisMethod: file
    GenesisProfile: SampleInsecureSolo
    GenesisFile: orderer.genesis.block
    LocalMSPDir: crypto-config/ordererOrganizations/atlchain.com/orderers/orderer.atlchain.com/msp
    LocalMSPID: Orderer
    Profile:
        Enabled: false
        Address: 0.0.0.0:6060

    BCCSP:
        Default: SW
        SW:
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:

    Authentication:
        TimeWindow: 15m

FileLedger:
    Location: orderer/production/orderer
    Prefix: hyperledger-fabric-ordererledger

RAMLedger:
    HistorySize: 1000

Kafka:
    Retry:
        ShortInterval: 5s
        ShortTotal: 10m
        LongInterval: 5m
        LongTotal: 12h

        NetworkTimeouts:
            DialTimeout: 10s
            ReadTimeout: 10s
            WriteTimeout: 10s

        Metadata:
            RetryBackoff: 250ms
            RetryMax: 3

        Producer:
            RetryBackoff: 100ms
            RetryMax: 3

        Consumer:
            RetryBackoff: 2s

    Verbose: false

    TLS:
      Enabled: false
      PrivateKey:
      Certificate:
      RootCAs:
    Version:

Debug:
    BroadcastTraceDir:
    DeliverTraceDir:
