# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
    ca0.atlchain.com:
    ca1.atlchain.com:
    orderero.orga.atlchain.com:
    peer0.orga.atlchain.com:
    peer1.orga.atlchain.com:
    peer0.orgb.atlchain.com:
    peer1.orgb.atlchain.com:

networks:
    byfn:
services:
    ca0.atlchain.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-org1
            - FABRIC_CA_SERVER_TLS_ENABLED=false
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orga.atlchain.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.orga.atlchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ./crypto-config/peerOrganizations/orga.atlchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca0.atlchain.com
        networks:
            - byfn

    ca1.atlchain.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - fABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - fABRIC_CA_SERVER_CA_NAME=ca-org2
            - fABRIC_CA_SERVER_TLS_ENABLED=false
            - fABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orgb.atlchain.com-cert.pem
            - fABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
        ports:
            - "8054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.orgb.atlchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ./crypto-config/peerOrganizations/orgb.atlchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca1.atlchain.com
        networks:
            - byfn

    orderer0.orga.atlchain.com:
        extends:
            file:   base/docker-compose-base.yaml
            service: orderer0.orga.atlchain.com
        container_name: orderer0.orga.atlchain.com
        networks:
            - byfn

    peer0.orga.atlchain.com:
        container_name: peer0.orga.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer0.orga.atlchain.com
        networks:
            - byfn

    peer1.orga.atlchain.com:
        container_name: peer1.orga.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer1.orga.atlchain.com
        networks:
            - byfn
    
    peer0.orgb.atlchain.com:
        container_name: peer0.orgb.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer0.orgb.atlchain.com
        networks:
            - byfn
    
    peer1.orgb.atlchain.com:
        container_name: peer1.orgb.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer1.orgb.atlchain.com
        networks:
            - byfn
